version: '3.8'
services:
  app:
    image: prometheus_demo
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/test'
      - '--web.external-url=http://localhost:9090/test'
    ports:
      - '9090:9090'

  renderer:
    image: grafana/grafana-image-renderer:3.4.2
    environment:
      BROWSER_TZ: Asia/Taipei
    ports:
      - '8081:8081'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana-storage:/var/lib/grafana"
    depends_on:
      - prometheus
      - renderer
    ports:
      - '3000:3000'